BEGIN TRANSACTION;
CREATE TABLE Fotos (IDFoto VARCHAR PRIMARY KEY NOT NULL, IDLugar INTEGER REFERENCES Lugares (IDLugar), Descripcion VARCHAR, Ruta STRING (0, 100));
CREATE TABLE DatosCargados (Condicion INTEGER PRIMARY KEY, Estado BOOLEAN);
CREATE TABLE Lugares (IDLugar INTEGER PRIMARY KEY NOT NULL, Descripcion VARCHAR, Video VARCHAR, Audio STRING (0, 100), TextoAudio STRING, Visitado BOOLEAN);
CREATE TABLE AudiosAdicionales (IDAudio VARCHAR PRIMARY KEY, Ruta STRING (0, 100), Descripcion VARCHAR, Texto VARCHAR);
CREATE TABLE Animaciones (IDAnimacion VARCHAR PRIMARY KEY, IDLugar INTEGER REFERENCES Lugares (IDLugar), Ruta STRING (0, 100), TextoAnimacion VARCHAR);
COMMIT;
